---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-router
  labels:
    app: wordpress-router
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-router
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-router
  labels:
    app: wordpress-router
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-router
    spec:
      containers:
      - name: mysqlrouter
        image: pulsepointinc/mysql-router:2.1.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-root-password
              key: password
        command:
        - "/bin/bash"
        - "-cx"
        - |
          echo "Bootstraping the router"
          echo $MYSQL_ROOT_PASSWORD | mysqlrouter --bootstrap mysql-wordpress-0.mysql-wordpress:3306 --user=root

          echo "Updating resolv.conf"
          search=$(grep ^search /etc/resolv.conf)
          echo "$search mysql-wordpress.default.svc.cluster.local" >> /etc/resolv.conf

          echo "Running the router"
          mysqlrouter --user=root
      - name: wordpress
        image: wordpress:4.8.0-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:6446
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-root-password
              key: password
        ports:
        - containerPort: 80
