# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Code generation dependencies
required = [
  "k8s.io/code-generator/cmd/client-gen",
  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",

  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "~1.0.0"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "~1.28.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "7f97868eec74b32b0982dd158a51a446d1da7eb5"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apiserver"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~6.0"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/code-generator"

[[constraint]]
  branch = "master"
  name = "k8s.io/utils"

[[constraint]]
  branch = "master"
  name = "github.com/heptiolabs/healthcheck"

[[override]]
  branch = "master"
  name = "k8s.io/gengo"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "df38d32658d8788cd446ba74db4bb5375c4b0cb3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.41"
