apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysql5clusters.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLCluster
    singular: mysql5cluster
    plural: mysql5clusters
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysql5backups.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLBackup
    singular: mysql5backup
    plural: mysql5backups
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysql5restores.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLRestore
    singular: mysql5restore
    plural: mysql5restores
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysql5backupschedules.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLBackupSchedule
    singular: mysql5backupschedule
    plural: mysql5backupschedules
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql5-operator
  namespace: mysql5-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql5-agent
  namespace: mysql5-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql5-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - create

  - apiGroups: [""]
    resources:
    - services
    - configmaps
    verbs:
    - create
    - get
    - list
    - watch

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysql5backups
    - mysql5backupschedules
    - mysql5clusters
    - mysql5clusters/finalizers
    - mysql5restores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysql5backups"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql5-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysql5backups
    - mysql5backupschedules
    - mysql5clusters
    - mysql5clusters/finalizers
    - mysql5restores
    verbs:
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: mysql5-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql5-operator
subjects:
- kind: ServiceAccount
  name: mysql5-operator
  namespace: mysql5-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: mysql5-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql5-agent
subjects:
- kind: ServiceAccount
  name: mysql5-agent
  namespace: mysql5-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql5-operator
  namespace: mysql5-operator
  labels:
    app: mysql5-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql5-operator
  template:
    metadata:
      labels:
        app: mysql5-operator
    spec:
      serviceAccountName: mysql5-operator
      containers:
      - name: mysql-operator-controller
        image: cuijx/mysql5-operator:v0.18.2
        imagePullPolicy: Always
        ports:
        - containerPort: 10254
        args:
          - --v=4
          - --mysql-agent-image=cuijx/mysql5-agent:v0.18.2